title: Celo Zaga
description: Stay updated with the latest mobile games news and the gaming industry, game releases, betas, leaks and more!
theme: null
baseurl: ""
url: "https://celozaga.github.io"
plugins:
  - jekyll-sitemap
  - jekyll-feed

social:
  discord: "gHEHaxtwBT"
  youtube: "celozaga"
  tiktok: "celozaga"
  bluesky: "celozaga.bsky.social"
  x: "celozaga"
  threads: "celozaga"
  reddit: "celozaga"
  digg: "celozaga"

collections:
  slides:
    output: false
  store:
    output: true
