backend:
  name: github
  repo: celozaga/celozaga.github.io
  branch: main
  # To test locally without setting up a server, uncomment the line below:
  # local_backend: true

# NOTE: If hosting on GitHub Pages, you need to set up Netlify or an OAuth server 
# for the 'github' backend to work. See walkthrough.md for instructions.

media_folder: "static/media"
public_folder: "/static/media"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "OG Type", name: "og_type", widget: "string", default: "video.other"}
      - {label: "Body", name: "body", widget: "markdown"}
